config/routes.rb
Gistapp::Application.routes.draw do

  get "follow_activity/follow"
  get "follow_activity/unfollow"
  get "follow_activity/update_follower"

  get "profiles/show"
 as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users,  :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}  do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :votes, :only => [:create]
  resources :comments, :only => [:create, :index] do
    get :new_child_comment, on: :member
    post :create_child_comment, on: :member
    get :up_vote, :member
  end

  resources :user_friendships do
    member do
      put :accept
  end
end

  resources :statuses do
    get 'vote', on: :member
    post 'vote', on: :member
  end
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :status
  attr_accessible :content, :status_id, :user_id, :ancestry, :parent_id

  has_ancestry

  has_reputation :up_vote,
                 :source => :user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @status_id = params[:status_id]
    @status = Status.find(@status_id)
    @comments = @status.comments
    @comment = @status.comments.build
    respond_to do |format|
      format.js
    end
  end

  def create
    if current_user
    @comment = Comment.new(params[:comment])
    @parent_id = nil
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Your reply has been posted successfully"
    else
      flash[:error] = "#{@comment.errors.full_messages.join(',')}"
    end
    @status = @comment.status
    @status_id = @status.id
    @comments = @status.comments
    @comment = @status.comments.build
    else
      flash[:error] = "You need to be logged in first"
    end
    respond_to do |format|
      format.js
    end
  end

  def new_child_comment
    @parent_comment = Comment.find(params[:id])
    @comment = Comment.new(parent_id: @parent_comment.id)
    respond_to do |format|
      format.js
    end
  end

  def create_child_comment
    if current_user
    @comment = Comment.new(params[:comment])
    @comment.user = current_user

    @parent_comment = Comment.find(params[:id])
    @status = @parent_comment.root.status
    @comment.status = @status
    if @comment.save
      flash[:notice] = "Your reply has been posted successfully"
    else
      flash[:error] = "#{@comment.errors.full_messages.join(',')}"
    end
    @comments = @status.comments
    @comment = @status.comments.build
    @status_id = @status.id
    else
      flash[:error] = "You need to be logged in first"
    end
    respond_to do |format|
      format.js
    end
  end

  def up_vote
    @comment_for_vote = Comment.find(params[:comment_id])
    @status = @comment_for_vote.root.status
    @comments = @status.comments
    @comment = @status.comments.build
    @user = current_user
    begin
      @comment_for_vote.add_evaluation(:up_vote, 1, @user)
      flash[:notice] = "Your vote has been successfully submitted"
    rescue
      if current_user.nil?
        flash[:error] = "You need to be logged in first"
      else
        flash[:error] = "You have already submitted a vote"
      end
    end
  end



end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="span6 well">
 <%= comment.content %>  <br />
  <p>By <%= comment.try(:user).try(:full_name) rescue "Anonimous" %></p>
<%= time_ago_in_words(comment.created_at) %> ago
<%= link_to 'reply', new_child_comment_comment_path(comment), remote: true %> |
<%= link_to '+1',  comment_up_vote_path(comment.id), remote: true  %>
  <div id="comment_form_for_<%= comment.id %>">

  </div>
</div>

app/views/comments/create.js.erb
<% if current_user %>
$("#notification").html("<%= escape_javascript(render partial: 'layouts/notification') %>")
$("#comment_form_for_status_<%= @status_id %>").html("<%= escape_javascript(render :partial => 'shared/comment_form', locals: {comment: @comment, status_id: @status_id, status: @status, comments: @comments}) %>")
<% else %>
$("#notification").html("<%= escape_javascript(render partial: 'layouts/notification') %>")
<% end %>

app/views/comments/create_child_comment.js.erb
<% if current_user %>
$("#notification").html("<%= escape_javascript(render partial: 'layouts/notification') %>")
$("#comment_form_for_status_<%= @status_id %>").html("<%= escape_javascript(render :partial => 'shared/comment_form', locals: {comment: @comment, status_id: @status_id, status: @status, comments: @comments, parent_id: nil}) %>")
<% else %>
$("#notification").html("<%= escape_javascript(render partial: 'layouts/notification') %>")
<% end %>

app/views/comments/index.js.erb
$("#comment_form_for_status_<%= @status_id %>").html("<%= escape_javascript(render :partial => 'shared/comment_form', locals: {comment: @comment, status_id: @status_id, status: @status, comments: @comments, parent_id: @parent_id}) %>")

app/views/comments/new_child_comment.js.erb
$("#comment_form_for_<%= @parent_comment.id %>").html("<%= escape_javascript(render :partial => 'shared/comment_reply_form', locals: {comment: @comment, parent_id: params[:id] }) %>")

app/views/comments/up_vote.js.erb
<% if current_user %>
$("#notification").html("<%= escape_javascript(render partial: 'layouts/notification') %>")
$("#comment_form_for_status_<%= @status_id %>").html("<%= escape_javascript(render :partial => 'shared/comment_form', locals: {comment: @comment, status_id: @status.id, status: @status, comments: @comments, parent_id: nil}) %>")
<% else %>
$("#notification").html("<%= escape_javascript(render partial: 'layouts/notification') %>")
<% end %>