config/routes.rb
Gistapp::Application.routes.draw do

  get "follow_activity/follow"
  get "follow_activity/unfollow"
  get "follow_activity/update_follower"

  get "profiles/show"
 as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users,  :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}  do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :votes, :only => [:create]
  resources :comments, :only => [:create, :index] do
    get :new_child_comment, on: :member
    post :create_child_comment, on: :member
    get :up_vote, :member
  end

  resources :user_friendships do
    member do
      put :accept
  end
end

  resources :statuses do
    get 'vote', on: :member
    post 'vote', on: :member
  end
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]


  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.order("created_at DESC") unless params[:tag]
    @statuses = Status.tagged_with(params[:tag].to_s,:on => :tags ,:any => true ) if params[:tag]
    if params[:time]
     @statuses =  @statuses.where(['created_at >= ? and created_at <= ?', params[:time], Time.zone.now.end_of_day])
    end
    authorize! :read, @statuses
    respond_to do |format|
      format.html # index.js.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])
    @comment = @status.comments.build
    @comments = @status.comments
    authorize! :read, @status
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new
    authorize! :create, @status
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
    authorize! :update, @status
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])
    authorize! :create, @status
    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    authorize! :update, @status
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id)
    end
    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    authorize! :destroy, @status
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  def vote
    @status = Status.find(params[:id])
    @user = current_user
    begin
      @status.add_evaluation(:votes, 1, @user)
      flash[:notice] = "Your vote has been successfully submitted"
    rescue
      if current_user.nil?
        flash[:error] = "You need to be logged in first"
      else
        flash[:error] = "You have already submitted a vote"
      end
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
	def url_to_link url
		"http://" + url
	end
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :tag_line %>(<p>Hint: type tags seperating by comma</p>)
  <%= f.input :url %>
  <%= f.input :content %>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<hr/>
<div class="span8">
  <% @statuses.each do |status| %>
      <div class="status">
        <div class="row">

          <div class="span3" style="padding: 10px">
            <div class="votes" style="">
              <div style="margin-top: 50px; font-size: 30px"><%= link_to '', vote_status_path(status), class: "typicn thumbsUp", remote: true %></div>
            </div>
            <div class="" style="padding-left: 40px;">
              <% if !status.content.empty? %>
                  <p><%= link_to status.title, status %></p>
              <% else %>
                  <h5 class="headline"><%= link_to status.title, url_to_link(status.url) %></h5>

                  <p class="sub-headline"><%= link_to status.url, status.url %></p>
              <% end %>
              <% unless status.tag_list.blank? %>
                  <%= status.tag_list.join(',') %>
              <% end %>
              <div class="meta">
                <span id="reputation-<%= status.id %>"><%= status.reputation_for(:votes).to_i rescue 0 %> points </span>
                <span>by <%= status.user.full_name %></span><br/>
                <span><%= link_to time_ago_in_words(status.created_at) + " ago", status %></span> |
                <%= link_to "#{status.comments.size.to_i rescue 0} comment", status_path(status), id: "close_#{status.id}", status: status.id %>
                <br/>
            <span class="admin">
          <% if can? :update, status %>
           <%= link_to "Edit", edit_status_path(status) %> |
          <% end %>
              <% if can? :destroy, status %>
          <%= link_to "Delete", status, method: :delete, data: {confirm: "Are you sure your want to delete this status?"} %>
          <% end %>
        </span>
              </div>
            </div>
            <div id="comment_form_for_status_<%= status.id %>">

            </div>
          </div>

          <div class="span2" style="margin-top: 10px">
            <table>
              <thead>
              <tr>
                <td style="text-align: center; padding: 20px">Votes</td>
                <td style="text-align: center; padding: 20px">Comments</td>
                <td style="text-align: center; padding: 20px">Views</td>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td style="text-align: center" id="reputation-<%= status.id %>"><%= status.reputation_for(:votes).to_i rescue 0 %></td>
                <td style="text-align: center"><%= status.comments.size rescue 0 %></td>
                <td style="text-align: center"><%= 0 %></td>
              </tr>
              </tbody>
            </table>
          </div>
          <div class="span1 pull-right gravatar-box" style="padding-top: 40px;">
            <%= image_tag status.user.gravatar_url %>
          </div>
        </div>
      </div>
  <% end %>
</div>

<div class="span3 pull-right tag-clouds">
  <h4>Trending Topic &nbsp;&nbsp;&nbsp;<i data-title="tag" class="typicn tag"></i></h4>
  <hr/>
  <% @tags = Status.tag_counts_on(:tags) %>
  <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <div class="row-fluid" style="margin-bottom: 10px">
        <%= link_to content_tag(:span, tag.name.capitalize, class: 'tag-style')+' x '+tag.count.to_s, root_path(tag:tag.name), :class => "#{css_class}", :style => "text-decoration:none" %>
      </div>
  <% end %>
</div>

app/views/statuses/new.html.erb
<h1>Submit a link</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<hr/>
<div class="span8">
      <div class="@status">
        <div class="row">

          <div class="span3" style="padding: 10px">
            <div class="votes" style="">
              <div style="margin-top: 50px; font-size: 30px"><%= link_to '', vote_status_path(@status), class: "typicn thumbsUp", remote: true %></div>
            </div>
            <div class="" style="padding-left: 40px;">
              <% if !@status.content.empty? %>
                  <p><%= link_to @status.title, @status %></p>
              <% else %>
                  <h5 class="headline"><%= link_to @status.title, url_to_link(@status.url) %></h5>

                  <p class="sub-headline"><%= link_to @status.url, @status.url %></p>
              <% end %>
              <% unless @status.tag_list.blank? %>
                  <%= @status.tag_list.join(',') %>
              <% end %>
              <div class="meta">
                <span id="reputation-<%= @status.id %>"><%= @status.reputation_for(:votes).to_i rescue 0 %> points </span>
                <span>by <%= @status.user.full_name %></span><br/>
                <span><%= link_to time_ago_in_words(@status.created_at) + " ago", @status %></span> |
                <%= link_to "#{@status.comments.size.to_i rescue 0} comment", status_path(@status), id: "close_#{@status.id}", status: @status.id %>
                <br/>
            <span class="admin">
          <% if can? :update, @status %>
           <%= link_to "Edit", edit_status_path(@status) %> |
          <% end %>
              <% if can? :destroy, @status %>
          <%= link_to "Delete", @status, method: :delete, data: {confirm: "Are you sure your want to delete this @status?"} %>
          <% end %>
        </span>
              </div>
            </div>
            <div id="comment_form_for_status_<%= @status.id %>">
                <%= render :partial => 'shared/comment_form', locals: {comment: @comment, status_id: @status.id, status: @status, comments: @comments, parent_id: nil} %>
            </div>
          </div>

          <div class="span2" style="margin-top: 10px">
            <table>
              <thead>
              <tr>
                <td style="text-align: center; padding: 20px">Votes</td>
                <td style="text-align: center; padding: 20px">Comments</td>
                <td style="text-align: center; padding: 20px">Views</td>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td style="text-align: center" id="reputation-<%= @status.id %>"><%= @status.reputation_for(:votes).to_i rescue 0 %></td>
                <td style="text-align: center"><%= @status.comments.size rescue 0 %></td>
                <td style="text-align: center"><%= 0 %></td>
              </tr>
              </tbody>
            </table>
          </div>
          <div class="span1 pull-right gravatar-box" style="padding-top: 40px;">
            <%= image_tag @status.user.gravatar_url %>
          </div>
        </div>
      </div>
</div>

<div class="span3 pull-right tag-clouds">
  <h4>Trending Topic &nbsp;&nbsp;&nbsp;<i data-title="tag" class="typicn tag"></i></h4>
  <hr/>
  <% @tags = @status.tag_counts_on(:tags) %>
  <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <div class="row-fluid" style="margin-bottom: 10px">
        <%= link_to content_tag(:span, tag.name.capitalize, class: 'tag-style')+' X '+tag.count.to_s, root_path(tag: tag.name), :class => "#{css_class}", :style => "text-decoration:none" %>
        <br/>
      </div>
  <% end %>
</div>

app/views/statuses/vote.js.erb
$("#notification").html("<%= escape_javascript(render partial: 'layouts/notification') %>")
$("td#reputation-<%= @status.id %>").html("<%= (@status.reputation_for(:votes)).to_i %>")
$("span#reputation-<%= @status.id %>").html("<%= (@status.reputation_for(:votes)).to_i %> points ")