config/routes.rb
Gistapp::Application.routes.draw do

  get "follow_activity/follow"
  get "follow_activity/unfollow"
  get "follow_activity/update_follower"

  get "profiles/show"
 as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users,  :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}  do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :votes, :only => [:create]
  resources :comments, :only => [:create, :index] do
    get :new_child_comment, on: :member
    post :create_child_comment, on: :member
    get :up_vote, :member
  end

  resources :user_friendships do
    member do
      put :accept
  end
end

  resources :statuses do
    get 'vote', on: :member
    post 'vote', on: :member
  end
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/_notification.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= flash_class type %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gistapp</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner" style="height: 70px;">
    <div class="container">
      <a href="/" class="brand" style="margin-top: 10px;"> gistapp</a>
      <ul class="nav">
        <li class="<%=  params[:name] == '1hour' ? 'active' : 'border' %>"><%= link_to "1 HOUR", feed_path(time: 1.hour.ago, name: '1hour') %></li>
        <li class="<%= params[:name] == 'today' ? 'active' : '' %>"><%= link_to "24 hours", feed_path(time: 24.hours.ago, name:'today') %></li>
        <li class="<%= params[:name] == 'week' ? 'active' : 'border' %>"><%= link_to "Week", feed_path(time: 7.days.ago, name: 'week') %></li>
      </ul>
      <ul class="nav pull-right site-nav">
        <li><%= link_to "Submit a link", new_status_path %></li>

        <% if user_signed_in? %>
            <li><%= link_to 'Friends', user_friendships_path %></li>
            <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
            <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
            <li><%= link_to "Register", register_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>

      </ul>
    </div>
  </div>
</div>
<div class="clearfix" style="height: 20px"></div>
<div class="container">
  <div class="span12">
    <div class="clearfix" style="height: 20px"></div>
    <div id="notification">
      <%= render partial: 'layouts/notification' %>
    </div>
    <%= yield %>
  </div>
</div>
</body>
</html>